name: silmaril-env
channels:
  - defaults
  - conda-forge
dependencies:
  - ipython
  - sphinx
  - scipy
  - numpy
  - matplotlib
  - tqdm
  - astropy
  - pip
  - python=3.11
  - sphinx-book-theme
  - myst-nb